# Generated by Django 6.0.7 on 2026-08-08 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editorprofile_full_name_journalistproflie_full_name_and_more'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.publisher'),
        ),
        migrations.CreateModel(
            name='JournalistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.publisher')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.journalistprofile'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.journalistprofile'),
        ),
        migrations.AlterField(
            model_name='readerprofile',
            name='journalists',
            field=models.ManyToManyField(to='accounts.journalistprofile'),
        ),
        migrations.DeleteModel(
            name='JournalistProflie',
        ),
    ]
