# Generated by Django 6.0.7 on 2026-08-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_article_thumbnail_newsletter_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumbnail',
            new_name='thumbnails',
        ),
    ]
