# Generated by Django 6.0.7 on 2026-08-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_thumbnail_article_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='thumbnail',
        ),
    ]
