# Generated by Django 6.0.7 on 2026-08-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_article_created_at_alter_newsletter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.editorprofile'),
            preserve_default=False,
        ),
    ]
