# Generated by Django 6.0.7 on 2026-08-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_newsletter_editor'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.publisher'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.journalistprofile'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.editorprofile'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.publisher'),
        ),
    ]
