# Generated by Django 6.0.7 on 2026-08-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_article_publisher_alter_newsletter_author_and_more'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorprofile',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='journalistprofile',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='publisher',
            field=models.ManyToManyField(to='content.publisher'),
        ),
        migrations.AddField(
            model_name='journalistprofile',
            name='publisher',
            field=models.ManyToManyField(to='content.publisher'),
        ),
    ]
