# Generated by Django 6.0.7 on 2026-08-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_editorprofile_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorprofile',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.RenameField(
            model_name='journalistprofile',
            old_name='publisher',
            new_name='publishers',
        ),
    ]
