from django.urls import path
from . import views

urlpatterns = [
    path(
        'publisher_summary/',
        views.publisher_summary,
        name='publisher_summary',
    ),
    path('newsletter_sum/', views.newsletter_sum, name='newsletter_sum'),
    path(
        'unapproved_articles/',
        views.unapproved_article,
        name='unapproved_articles',
    ),
    path(
        'add_article/',
        views.add_article,
        name='add_article',
    ),
    path(
        'approve_article/<id>/',
        views.approve_article,
        name='approve_article',
    ),
    path(
        'edit_article/<id>/',
        views.edit_article,
        name='edit_article',
    ),
    path(
        'delete_article/<id>/',
        views.delete_article,
        name='delete_article',
    ),
    path(
        'add_newsletter/',
        views.add_newsletter,
        name='add_newsletter',
    ),
    path(
        'edit_newsletter/<id>/',
        views.edit_newsletter,
        name='edit_newsletter',
    ),
    path(
        'delete_newsletter/<id>/',
        views.delete_newsletter,
        name='delete_newsletter',
    ),
    path(
        'add_publisher/',
        views.add_publisher,
        name='add_publisher',
    ),
    path(
        'edit_publisher/<id>/',
        views.edit_publisher,
        name='edit_publisher',
    ),
    path(
        'delete_publisher/<id>/',
        views.delete_publisher,
        name='delete_publisher',
    ),
    path(
        'subscribe_publisher/<id>/',
        views.subscribe_publisher,
        name='subscribe_publisher',
    ),
    path(
        'subscribe_journalist/<int:pk>/',
        views.subscribe_journalist,
        name='subscribe_journalist',
    ),
    path(
        'subscribe/',
        views.subscribe,
        name='subscribe',
    ),
    path(
        'unsubscribe_publisher/<id>/',
        views.unsubscribe_publisher,
        name='unsubscribe_publisher',
    ),
    path(
        'unsubscribe_journalist/<int:pk>/',
        views.unsubscribe_journalist,
        name='unsubscribe_journalist',
    ),
    path(
        'journalist_coverage/<full_name>/',
        views.journalist_coverage,
        name='journalist_coverage',
    ),
    path(
        'journalist_summary/',
        views.journalist_summary,
        name='journalist_summary'
    ),
    path(
        'view_publisher/<id>/',
        views.view_publisher,
        name='view_publisher',
    ),
    path(
        'view_article/<id>/',
        views.view_article,
        name='view_article',
    ),
    path(
        'view_newsletter/<id>/',
        views.view_newsletter,
        name='view_newsletter',
    ),
    path(
        'article_summary/',
        views.article_summry,
        name='article_summary',
    ),
    path(
        'join_publisher/',
        views.join_publisher,
        name='join_publisher',
    ),
]
